build-binary:
  image: golang:1.15-buster
  stage: build
  artifacts:
    expire_in: 1 day
    paths:
      - ./go-peek.gz
  script:
    - go get -u ./
    - go build -o ./go-peek ./
    - ./go-peek --help
  after_script:
    - gzip go-peek
  rules:
    - if: '$CI_BUILD_TAG =~ /^build-.*/'
